runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3


#[START gae_flex_storage_yaml]
env_variables:
    CLOUD_STORAGE_BUCKET: hello-app-306300
    DB_USER: postgres
    DB_PASS: jobhaven
    DB_NAME: postgres
    CLOUD_SQL_CONNECTION_NAME: hello-app-306300:us-east1:jobsagesql1
    db_hostname: 35.243.247.215
    db_port: 5432
    db_socket_dir: /cloudsql
#[END gae_flex_storage_yaml]